(10 points) Write a function that does the following:
1. takes a matrix A as an input
2. returns the reduced row echelon form of the matrix. (Remember to test your program with
corner cases.)
Your electronic submission should include a copy of your program, together with the output for the
following input matrix

01234 A=0 0 5 0 0
00000
Remark:You may work together in groups of 2 on your code. If so, each of you should submit the assignment for grading, together with the statement ”Worked with <name> on this programming assignment.”

In [78]:
def reducedref(matrix):
    import numpy as np 
    matrix = np.array([[0,1,2,3,4],[0,0,5,0,0],[0,0,0,0,0]]) #assigned matrix 
    r,c = matrix.shape #labeling the matrix dimensions  
    i= 0 #making counter 
    print(matrix) #printing initial matrix
    for j in range(c): # looking at the columns 
        if i >= r: #comparing counter and where it breaks to examine the kill
            break 
        big = np.argmax(np.abs(matrix[i:,j])) + i # finds value & index of largest entry 
        if matrix[big, j] == 0: #we want to continue on to the nexrt column even though there is a zero 
            continue 
        matrix[[i,big]] = matrix[[big,i]] #switching rows 
        pivot_value = matrix[i,j] #labeling pivot 
        matrix[i] = matrix[i] / pivot_value #divide the pivot row i by the pivot value to replace row 
        for k in range(r): # looking at the row 
            if k == i or matrix[k,j] == 0: # skipping the situations that have placements with 0's 
                continue
            value = matrix[k,j] # giving variable to value of number in position 
            matrix[k] = matrix[k] - value * matrix[i] #preforming -k/p to create 0's
        i = i + 1 #couter
    return matrix #prints reduced row echelon form matrix 

In [79]:
reducedref(matrix) #the matrix changes and now is in reduced row echelon form 

[[0 1 2 3 4]
 [0 0 5 0 0]
 [0 0 0 0 0]]


array([[0, 1, 0, 3, 4],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0]])

 Worked with Rachel Pedro on this programming assignment.
