(10 points) Write a function that does the following:
1. takes a matrix A as an input
2. returns the reduced row echelon form of the matrix. (Remember to test your program with
corner cases.)
Your electronic submission should include a copy of your program, together with the output for the
following input matrix

01234 A=0 0 5 0 0
00000
Remark:You may work together in groups of 2 on your code. If so, each of you should submit the assignment for grading, together with the statement ”Worked with Rachel Pedro on this programming assignment.”

In [123]:
A= np.array([[0,0,0,0,0],[0,0,0,-1,2],[0,2,0,4,2]])
import numpy as np 
def reducedref(A):
    r,c = A.shape #labeling the matrix dimensions  
    i= 0 #making counter
    pivotindex=[] #empty matrix for pivot index
    print(A)
    for j in range(c): # looking at the columns 
        if i >= r: #comparing counter and where it breaks to examine the kil
            break 
        kill = np.argmax(np.abs(A[i:,j])) + i # finds k (the number we want to kill) 
        if A[kill, j] == 0: #we want to continue even though there is a zero 
            continue 
        A[[i,kill]] = A[[kill,i]] #switching rows 
        pivot_value = A[i,j] #labeling pivot 
        A[i] = A[i] / pivot_value #divide the pivot row i by the pivot value 
        for k in range(r): # looking at the row 
            if k == i or A[k,j] == 0: # skipping the placements with 0's 
                continue
            value = A[k,j] # giving variable to value of number in position 
            A[k] = A[k] - value * A[i] #preforming -k/p to create 0's
        i = i + 1 #couter
    pivotindex.append(np.where(A==1)) #appends pivot index  
    return A, pivotindex #prints reduced row echelon form matrix and pivots  

In [124]:
reducedref(A)

[[ 0  0  0  0  0]
 [ 0  0  0 -1  2]
 [ 0  2  0  4  2]]


(array([[ 0,  1,  0,  0,  5],
        [ 0,  0,  0,  1, -2],
        [ 0,  0,  0,  0,  0]]),
 [(array([0, 1]), array([1, 3]))])