Homework 1: 

1. Write a function that does the following: 1. takes a matrix A and an integer k as inputs computes Ak = AA . . . A (the product of k matrices A) if the matrix is square, i.e., has the same number of rows and colums, and computes the transpose of A otherwise 3. returns the result of the computation

In [5]:
import numpy as np 
import random

In [22]:
#random number generator that powers a random matrix 
def my_func1(k): 
    a= random.randint(0,9)
    b= random.randint(0,9)
    c=random.randint(0,9)
    d=random.randint(0,9)
    e= random.randint(0,9)
    f=random.randint(0,9)
    g=random.randint(0,9)
    h=random.randint(0,9)
    i=random.randint(0,9)
    j=random.randint(0,9)
    
    A = np.array([[a, b, c, d, e], [f, g, h, i, j]])
    
    ans = A^k
    print(ans)
    
my_func1(3)

[[ 7  3  0  2 10]
 [ 3  4  7  7 10]]


In [50]:

E = np.array([[1, 3, 5, 7, 9], [2, 4, 6, 8, 10]])

K = np.array([[1, 2, 3, 4, 5], [5, 4, 3, 2, 1]])

In [59]:
#transpose if the dimensions doesnt work out 
np.matmul(K.T,E)

array([[11, 23, 35, 47, 59],
       [10, 22, 34, 46, 58],
       [ 9, 21, 33, 45, 57],
       [ 8, 20, 32, 44, 56],
       [ 7, 19, 31, 43, 55]])

In [57]:
E

array([[ 1,  3,  5,  7,  9],
       [ 2,  4,  6,  8, 10]])

In [49]:
#matrix power passing in random matrix and power
a=random.randint(0,9)
b=random.randint(0,9)
c=random.randint(0,9)
d=random.randint(0,9)
e=random.randint(0,9)
f=random.randint(0,9)
g=random.randint(0,9)
h=random.randint(0,9)
i=random.randint(0,9)
j=random.randint(0,9)
    
A = np.array([[a, b, c, d, e], [f, g, h, i, j]])
    
def matrixpower(A,k): 
    
    ans = A^k
    print(ans)

In [51]:
matrixpower(A, 3)

[[4 5 6 3 3]
 [3 7 4 1 1]]


2. Why is AB != BA in general? Check your answer with the following matrix pairs:
A1andA2, A3andA4, A3andA5

In [6]:
#matrix multiplication
m1 = np.array([[1, 2],[3, 4]])
m2 = np.array([[1, 1],[-1, 1]])
m3 = np.array([[1, 1, 1], [-1, 2, 1]])
m4 = np.array([[1, 1], [2, 1], [1, -1]])
m5 = np.array([[1, 1], [2, 1]]) 

In [45]:
def matrixmult(a,b):
    if len(m1[0]) != len(m2):
        return([])
    else: 
        return np.matmul(m1,m2)      

In [32]:
#its a square matrix which works --- multiplying m1m2, m2m1 different outcomes 
np.matmul(m1,m2)

array([[-1,  3],
       [-1,  7]])

In [33]:
np.matmul(m2,m1)

array([[4, 6],
       [2, 2]])

In [38]:
np.matmul(m4,m3) 

array([[ 0,  3,  2],
       [ 1,  4,  3],
       [ 2, -1,  0]])

In [39]:
np.matmul(m3,m4)

array([[4, 1],
       [4, 0]])

In [43]:
#np.matmul(m3,m5) -- doesnt work, 2 diff sizes, use traspose 

In [62]:
np.matmul(m3.T,m5)

array([[-1,  0],
       [ 5,  3],
       [ 3,  2]])

In [44]:
np.matmul(m5,m3)

array([[0, 3, 2],
       [1, 4, 3]])